config/routes.rb
ChatDemo::Application.routes.draw do
  devise_for :users

  
  authenticated :user do
    root 'users#index'
  end
 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
 
  resources :conversations do
    resources :messages
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  
  has_many :messages, dependent: :destroy
  
  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end
 
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :conversation
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :conversations, :foreign_key => :sender_id
  
  before_create :set_name
  
  def set_name
    email = self.email.split('@')
    self.name = email[0]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :authenticate_user!
 
  layout false
 
  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
 
    render json: { conversation_id: @conversation.id }
  end
 
  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end
 
  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
 
  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    get_all_messages
  end
 
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!
 
    @path = conversation_path(@conversation)
  end

  
  #def create
    #@message = Message.create!(message_params)
    #PrivatePub.publish_to("/messages/new", "alert('#{@message.content}');")
    #get_all_messages
  #end
  
  private
  
  def message_params
    params.require(:message).permit(:content)
  end
  
  def get_all_messages
    @messages = Message.all
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all - [current_user]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end
 
  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead" id = "<%= @conversation.id %>" >
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
 
    <h1><%= @reciever.try(:name) %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :content, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
 
<%= subscribe_to conversation_path(@conversation) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <title>ChatDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<li class="<%=  self_or_other(message) %>">
  <div class="avatar">
    <img src="http://placehold.it/50x50" />
  </div>
  <div class="chatboxmessagecontent">
    <p><%= message.content %></p>
    <time datetime="<%= message.created_at %>" title="<%= message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= message_interlocutor(message).try(:name) %> • <%= message.created_at.strftime("%H:%M %p") %>
    </time>
  </div>
</li>

app/views/messages/create.js.erb
<% publish_to @path do %>
  var id = "<%= @conversation.id %>";
  var chatbox = $("#chatbox_" + id + " .chatboxcontent");
  var sender_id = "<%= @message.user.id %>";
  var reciever_id = $('meta[name=user-id]').attr("content");
 
  chatbox.append("<%= j render( partial: @message ) %>");
  chatbox.scrollTop(chatbox[0].scrollHeight);

  if(sender_id != reciever_id){
    chatBox.chatWith(id);
      chatbox.children().last().removeClass("self").addClass("other");        
    chatbox.scrollTop(chatbox[0].scrollHeight);
      chatBox.notify();
  }
<% end %>

app/views/messages/index.html.erb
<h1>Chat</h1>

<ul id="chat">
  <% @messages.each do |message| %>
    <%= render message %>
  <% end %>
</ul>

<%= form_for :message, url: messages_path ,remote: true, :html => {:id => 'new_message'} do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/new" %>

app/views/users/index.html.erb
<%= link_to 'Logout', destroy_user_session_path, method: :delete %><br/>
<table class="table table-bordered table_size">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Send message</th>
    </tr>
  </thead>
  <tbody>
    <% if @users.present? %>
      <% @users.each_with_index do |user, index| %>
        <tr>
          <td><%= index +=1 %></td>
          <td><%= user.try(:name) %></td>
          <td>
            <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" => user.id %>
          </td>
        </tr><br />
      <% end %>
    <% else %>
      <tr class='remove_text'><th>"No user present for chat."</th></tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>